squads = {
        'Stealth Experts'           : ['Twitch', 'Rengar', 'Evelynn', 'Kha\'zix'],
        'Dunkmasters'               : ['Jarvan IV', 'Darius', 'Vi', 'Master Yi', 'Yasuo'],
        'Second Chance'             : ['Anivia', 'Zac', 'Zilean', 'Aatrox', 'Ekko'],
        'The Ol\' Razzle Dazzle'    : ['Aurelion Sol', 'Taric', 'Bard', 'Lux', 'Karma'],
        'Master Snipers'            : ['Jayce', 'Caitlyn', 'Jinx', 'Jhin', 'Ezreal'],
        'Lethal Trampoline'         : ['Malphite', 'Alistar', 'Singed', 'Nautilus', 'Gragas'],
        'The Ascended'              : ['Azir', 'Renekton', 'Xerath', 'Nasus', 'Sivir'],
        'World Travelers'           : ['Shen', 'Pantheon', 'Twisted Fate', 'Rek\'sai', 'Nocturne'],
        'Femme Fatales'             : ['Ahri', 'Akali', 'Riven', 'Katarina', 'Irelia'],
        'Not Today'                 : ['Kayle', 'Lulu', 'Kindred', 'Tahm Kench', 'Kalista'],
        'Demacia\'s Heroes'         : ['Garen', 'Shyvana', 'Quinn', 'Xin Zhao', 'Poppy'],
        'Immortal Reminder'         : ['Soraka', 'Nami', 'Janna', 'Fiora', 'Sona'],
        'Voidspawn'                 : ['Kog\'maw', 'Cho\'gath', 'Vel\'koz', 'Malzahar', 'Kassadin'],
        'Animal Instincts'          : ['Warwick', 'Gnar', 'Fizz', 'Volibear', 'Wukong'],
        'Noxus\' Villains'          : ['Draven', 'LeBlanc', 'Cassiopeia', 'Swain', 'Urgot'],
        'Jungle Destroyers'         : ['Udyr', 'Lee Sin', 'Shaco', 'Nunu', 'Nidalee'],
        'Island Terrors'            : ['Hecarim', 'Maokai', 'Mordekaiser', 'Thresh', 'Yorick'],
        'The Chosen'                : ['Diana', 'Leona', 'Elise', 'Illaoi', 'Karthus'],
        'Thick Skin'                : ['Dr. Mundo', 'Sion', 'Skarner', 'Rammus', 'Trundle'],
        'Snow and Ice'              : ['Ashe', 'Braum', 'Lissandra', 'Sejuani', 'Olaf'],
        'Wombo Me Up Fam'           : ['Amumu', 'Fiddlesticks', 'Orianna', 'Miss Fortune', 'Kennen'],
        'Yordle Brigade'            : ['Teemo', 'Tristana', 'Corki', 'Heimerdinger', 'Veigar'],
        'Firepower'                 : ['Annie', 'Brand', 'Rumble', 'Gangplank', 'Ziggs'],
        'Mage You Look'             : ['Morgana', 'Ryze', 'Syndra', 'Viktor', 'Zyra'],
        'Carry Me'                  : ['Graves', 'Kog\'maw', 'Varus', 'Vayne', 'Lucian'],
        'The Breakfast Club'        : ['Blitzcrank', 'Jax', 'Tryndamere', 'Vladimir', 'Zed']
    }
